### ISSUE TITLE
Suggestion: Change github file structure to match game.

### ISSUE THREAD

**Issue by bluemetaknight** [LiddulBOFH/advanceandsecure#1]
Cloning the repo into the gamemodes folder results in git placing the files in
garrysmod\gamemodes\advanceandsecure\gamemodes\advanceandsecure

This obviously will not load properly into gmod. If you could change the structure such that it clones into
garrysmod\gamemodes\advanceandsecure, that would make updating versions a bit easier.

If there is a reason behind the current structure, then just close this at your convenience.

**Comment by LiddulBOFH** [comment]
Its actually intended to be cloned into garrysmod/addons, which is how the server is loading it, originally it was to be cloned into gamemodes as expected, but this was simpler for the auto-update script I have running on the server, so it didn't have to traverse multiple directories.
![image](https://github.com/user-attachments/assets/1662668a-d123-4eba-81f0-3e303cd21b13)

**Comment by LiddulBOFH** [comment]
That being said, I'll add to the readme where this should be cloned.
